### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by fcrbe** [z1c0/dashydash#1]
I'm missing some docu and tried to setup the project (on a local PC though, not yet a Raspberry).

After executing npm install and gulp, the page seems to be up and running, but only results in the below:
![image](https://user-images.githubusercontent.com/14942750/47725113-405efd80-dc58-11e8-9b4d-b757ad220570.png)

As a sidenote, I'm getting this error after startup (I assume it contains some (API)keys or sensitive data, but it's unclear what should/could be in it and how it should look like.
![image](https://user-images.githubusercontent.com/14942750/47725226-77351380-dc58-11e8-91a7-3b47f6d201e0.png)

Seems like a nice project and certainly something I might want to explore with three kids and myself being tech-savvy :-) As a disclaimer, I did not yet dive into the code too deep. New to Node.js and React.

Thanks for putting the project on Github though!

**Comment by pkshiu** [comment]
- You should be hitting localhost:3000
- there is a file call secrets.template.json in the src directory. Copy / rename it secrets.json. There is where you put your personal configuration/keys
- I am also playing with this and have it running and started to add to it. You need to get some keys from services that you use, e.g. todoist, weather etc as well.

**Comment by fcrbe** [comment]
Just figured it out as well :-) Thanks @pkshiu

**Comment by z1c0** [comment]
Wow, thank you @pkshiu for that quick response!
I did not expect someone jumping in here.
I have to apologize for the poor documentation and the code / modules being tailored to my personal needs at the moment.
Seeing someone else working with  dashydash is a great motivation and I will try and put some future effort into making it easier to use.

**Comment by pkshiu** [comment]
You are more than welcome @z1c0 ! Your code base fits my need after searching around a lot. It's really useful. I forked the project and has started to add to it, and make it more configurable. I will definitely PR those back to you. Right now I am trying to integrate google photos better since they keep changing their API, so that I can do the OAuth authentication via a web interface.
